//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2ISO810.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IDEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
    }
}

